backend:
  name: github
  repo: SerhiyGreench/OlehSobchenko.me-Content
  branch: main

locale: uk

i18n:
  structure: single_file
  locales: [uk, en]
  default_locale: uk

media_folder: "uploads"
public_folder: "uploads"
custom_stylesheet: "/admin/index.css"

collections:
  - name: posts
    label: Дописи
    folder: content/posts
    create: true
    slug: "{{path}}"
    format: json
    i18n: true
    editor:
      preview: false
    fields:
      - label: ID
        name: id
        widget: uuid
        i18n: duplicate
        required: true
      - label: "Шлях (допис буде доступний за цим шляхом у посиланні)"
        name: path
        widget: string
        hint: "Намагайтеся створити якомога коротший шлях, надавайте перевагу використанню транслітерованого шляху латиницею"
      - label: Заголовок
        name: title
        widget: string
        i18n: true
      - label: "Тіло допису"
        name: description
        widget: markdown
        i18n: true
  - name: categories
    label: Категорії
    folder: content/categories
    create: true
    slug: "{{id}}"
    format: json
    i18n: true
    fields:
      - label: ID
        name: id
        widget: uuid
        i18n: duplicate
        required: true
      - label: Назва
        name: name
        widget: string
        i18n: true
  - name: types
    label: Типи дописів
    folder: content/types
    create: true
    slug: "{{id}}"
    format: json
    i18n: true
    fields:
      - label: ID
        name: id
        widget: uuid
        i18n: duplicate
        required: true
      - label: Назва
        name: name
        widget: string
        i18n: true